**Numpy:Pacakge for Multidimensional array**

In [1]:
import numpy as np

In [2]:
arr=np.array ([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:

np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(3,2)

array([[0.55885557, 0.2790555 ],
       [0.04338288, 0.41971352],
       [0.06630792, 0.58923985]])

In [13]:
np.random.randn(3,2)

array([[-0.38402096, -0.58090653],
       [ 0.06518611, -0.67011315],
       [ 1.39376032, -1.06509106]])

In [17]:
np.random.randint(1,2)

1

In [18]:
rand_array=np.random.randint(0,100,20)

In [19]:
np.random.randint(20,56,100)

array([37, 49, 52, 21, 28, 45, 33, 24, 48, 53, 36, 37, 28, 47, 24, 48, 34,
       28, 30, 33, 22, 29, 42, 25, 29, 21, 27, 48, 46, 24, 34, 36, 31, 23,
       51, 41, 36, 52, 46, 49, 42, 48, 32, 45, 35, 38, 40, 42, 44, 35, 47,
       27, 32, 31, 39, 28, 31, 52, 26, 31, 28, 33, 43, 53, 29, 53, 52, 42,
       43, 30, 22, 55, 20, 31, 20, 37, 52, 33, 25, 51, 31, 45, 23, 31, 37,
       35, 30, 53, 50, 23, 33, 35, 54, 55, 27, 49, 21, 34, 44, 45])

In [20]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [22]:
rand_array.min()

3

In [23]:
rand_array.argmin()

6

In [24]:
sample_array[3:7]

array([3, 4, 5, 6])

In [29]:
sample_array=np.arange(10,21)

In [30]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [31]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [32]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [33]:
subset_sample_array=sample_array[1:4]=1001
subset_sample_array

1001

**Two Dimensional array**

In [34]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [35]:
sample_matrix[0][2]

1

In [36]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [38]:
sample_matrix[2]

array([56, 76, 24,  7])

In [41]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])